### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN when using private hosted npm registry

### ISSUE THREAD

**Issue by dylang** [dominictarr/npmd#78]
```
/usr/local/lib/node_modules/npmd/index.js:95
    if(err) throw err
                  ^
Error: SELF_SIGNED_CERT_IN_CHAIN
    at SecurePair.<anonymous> (tls.js:1367:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:979:10)
    at CleartextStream.read [as _read] (tls.js:471:13)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
```

Our registry is behind a firewall so I don't have a way to provide a test case but I'm happy to try out a work in progress branch. FWIW the classic npm client works with our registry, as have tools that use the classic npm apis such as [npm-check](https://www.npmjs.org/package/npm-check).

**Comment by tomek-he-him** [comment]
:+1:

Self-signed certificates and NPM are a real pain in the ass. We install some dependencies directly over HTTPS. The only solution that works with _npm_ for us is `npm install --strict-ssl=false`.

I wanted to give _npmd_ a try. And here’s what I get:

```
.../npmd/index.js:95
    if(err) throw err
                  ^
Error: DEPTH_ZERO_SELF_SIGNED_CERT
    at SecurePair.<anonymous> (tls.js:1381:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
```

**Comment by dominictarr** [comment]
Oh hmm... okay so the ideal solution would be to be able to configure a cert to use for a particular domain, right?

I would be happy to merge a PR that allowed you to set certs, and to answer any questions necessary.

**Comment by tomek-he-him** [comment]
> to be able to configure a cert to use for a particular domain

Yeah, so we’ve tried with _npm_ – and after a several hours’ fight we gave up – and decided to pull our HTTPS modules with the option `--strict-ssl=false`.

@dylang was that why you migrated off HTTPS?

How about forwarding any options to _npm_? So you could just do `npmd install --strict-ssl=false`.

**Comment by dominictarr** [comment]
well the strict-ssl option is actually a thing that is being passed to request. npmd doesn't depend on npm.

**Comment by dylang** [comment]
@tomekwi We migrated to http because of (from what we can remember) couch issues with our cert and trust store and we didn't care to spend time trying to resolve because our registry is inside our firewall.
